Add Playwright UI Tests and Integration Tests for Search and Product Details Pages
cs4218/cs4218-project-2024-team04 pull request #34
Opened 2024-10-18 15:51 UTC by DanielLimWeiEn

2024-10-20 16:22 UTC, EvitanRelta requested changes
remove `.env.test`

2024-10-20 16:22 UTC, EvitanRelta commented on .env.test
remove this file. `.env` files shouldn't be commited

2024-10-20 16:22 UTC, EvitanRelta commented on tests-examples/demo-todo-app.spec.cjs
what this for?

2024-10-25 20:20 UTC, swxk19 commented on tests-examples/demo-todo-app.spec.cjs
auto-generated by playwright upon installation. can be removed

2024-10-27 10:58 UTC, merged